<h1>Sehr geehrte Damen und Herren,</h1>
<p>wir wenden uns heute an Sie, weil die das Produkt "{{ product }}" anbieten.<p>
<p><strong>{{ entriesamount }}</strong> Verbraucher haben über unsere Smartphone-App replacePlastic angegeben, dass sie sich Ihr Produkt "{{ product }}" in einer Verpackung ohne Plastik/mit weniger Plastik wünschen.</p>
<p>Plastikmüll in den Meeren stellt ein großes Problem dar, weshalb immer mehr Verbraucher ein Bewusstsein für dieses Thema zeigen. Viele Menschen wünschen sich plastikfreie Verpackungen. Aus diesem Grund senden wir Ihnen heute die Wünsche der Verbraucher zu Ihrem Produkt.</p>
<p>Wir hoffen, dass diese Information über die Wünsche und Werte Ihrer Zielgruppen Sie hilfreich ist, um bessere Lösungen für Ihre Kunden zu verwirklichen.</p>
<p>Für mehr Informationen zu unserem Projekt besuchen Sie gern unsere Website <a href="http://www.replaceplastic.de">ReplacePlastic.de</a></p>
<p>Mit freundlichen Grüßen,<br/>das Team vom Verein Küste gegen Plastik e.V.</p>
